### ISSUE TITLE
No automatic installation of castxml on Ubuntu 16.04

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/package_set#116]
castxml is not automatically installed on ubuntu 16.04.
Therefore orogen packages fail as autoproj tries to 
build them using (the also not installed) gccxml.

**Comment by doudou** [comment]
I'm bootstrapping a 16.04 in a fresh container, and it does get installed. Check that you have the latest from `package_set`, there was a bug in the loader selection that got fixed by https://github.com/rock-core/package_set/pull/115

**Comment by jmachowinski** [comment]
Did you choose ne CXX11 in your test ?

**Comment by doudou** [comment]
No

**Comment by doudou** [comment]
Yes, I chose no C++11

**Comment by jmachowinski** [comment]
hm, odd. Perhaps the bug of 115 hit me. Closing...
