### ISSUE TITLE
cxx11.rb incompatible with autoproj v1

### ISSUE THREAD

**Issue by 2maz** [rock-core/package_set#121]
cxx11.rb: Autoproj::OSPackageResolver is only known to autoproj v2, and effectively preventing the continued use of autoproj v1 installations without upgrading

**Comment by doudou** [comment]
Ack ... I'll look into it.

Question: how long do we intend to support Rock master on autoproj v1 ?

**Comment by doudou** [comment]
Try #122 out ...
