### ISSUE TITLE
Where to put vizkit3d_debug_drawings

### ISSUE THREAD

**Issue by arneboe** [rock-core/package_set#146]
I am in the process of publishing the [vizkit3d_debug_drawings library](https://github.com/rock-gui/gui-vizkit3d_debug_drawings) and would like to add it the rock-core package_set.

It depends on the following packages:
* gui/vizkit3d (rock-core package_set)
* gui/rock_widget_collection (rock-core package_set)
* gui/osgviz (rock-core package_set)
* base/boost_serialization (envire package_set)
* tools/orocos_cpp (rock-cpp package_set)

 For this to work  `base/boost_serialization` and `tools/orocos_cpp` would have to be moved to rock-core as well. 

What do you think @doudou ?

**Comment by doudou** [comment]
What is `boost_serialization` ?

**Comment by doudou** [comment]
I would prefer that you remove the orocos_cpp dependency given that you are pulling it for two lines of code. Moreover, it would be simpler (and more in line with the general workflow) to create a simple orogen plugin that would import the "right" typekit at the orogen level, removing the need to have a dynamic way to look for typekits and a need to dynamically create ports (with the added IMPORTANT plus to not sneakily create a port). With this done, you could also decide to keep the current code but make it optional (i.e. in which case you fail if the typekits you need are not available).

- from my perspective, to move this package to rock-core, you would have to at least follow the minimum of coding style guidelines, that is:
  - headers are `.hpp`
  - namespace is `snake_case`

Minor thing: don't use `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`. Use instead CMake's support for picking the C++ standard ([documentation here](https://www.rock-robotics.org/rock-and-syskit/libraries/cpp_libraries.html#cxx_standard))

**Comment by arneboe** [comment]
> I would prefer that you remove the orocos_cpp dependency given that you are pulling it for two lines of code. Moreover, it would be simpler (and more in line with the general workflow) to create a simple orogen plugin that would import the "right" typekit at the orogen level, removing the need to have a dynamic way to look for typekits and a need to dynamically create ports (with the added IMPORTANT plus to not sneakily create a port). With this done, you could also decide to keep the current code but make it optional (i.e. in which case you fail if the typekits you need are not available).

I'll look into this. Since I am doing nearly no work with orogen writing a orogen plugin never crossed my mind.

> 
>     * from my perspective, to move this package to rock-core, you would have to at least follow the minimum of coding style guidelines, that is:
>       
>       * headers are `.hpp`
>       * namespace is `snake_case`
ok.


> 
> Minor thing: don't use `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`. Use instead CMake's support for picking the C++ standard ([documentation here](https://www.rock-robotics.org/rock-and-syskit/libraries/cpp_libraries.html#cxx_standard))

done

**Comment by arneboe** [comment]
> What is `boost_serialization` ?
https://github.com/envire/base-boost_serialization

I just discovered that I already got rid of the dependency last year and just forgot to modify the manifest...

**Comment by arneboe** [comment]
> removing the need [...] to dynamically create ports (with the added IMPORTANT plus to not sneakily create a port). 

Removing the need for dynamically creating ports is not possible. The port names are not known at compile time.


Are there any resources on creating orogen plugins that load typekits? The rock-robotics manual documentation is not very helpful :(

**Comment by doudou** [comment]
> The port names are not known at compile time.

Why is it so ? I'm sorry, I know I'm asking you to explain to me the library workflow ...

**Comment by doudou** [comment]
The documentation for plugins is `https://www.rock-robotics.org/documentation/orogen/plugins.html`

As for typekits, if your plugin defines dynamic ports and/or ports, the corresponding typekits will be loaded automatically.

I still would like to investigate making the ports static, but in worst case, declaring the ports with

~~~
dynamic_output_port /^debug_/, '/datatype'
~~~

would be enough (load the data type definition first with 

~~~
project.using_library('vizkit3d_debug_drawings')
project.import_types_from('header.hpp')
~~~

**Comment by arneboe** [comment]
> Why is it so ? I'm sorry, I know I'm asking you to explain to me the library workflow ...

The library enables the user to draw from anywhere inside the code for debugging purposes, much like printf but in 3D. To reduce clutter the user can draw on different "canvases", each identified by a unique name. The canvases are created upon first use. Each canvas uses its own port. This way the user can focus on certain aspects when debugging (and reduce network load).
The canvas names are user defined literals that can be anywhere (e.g. in a library that is used by a library that is used by a task). 

However, using different ports for different canvases is purely a design decision. Technically it would be possible to define just one debug_port statically and send all drawings through that port. Canvas selection could then be done inside the vizkit plugin.

From my point of view having dynamically ports is not a problem as the whole purpose of this library is debugging.

**Comment by doudou** [comment]
> From my point of view having dynamically ports is not a problem as the whole purpose of this library is debugging.

From mine it is, as one won't be logging the debugging ports if they aren't declared.

One thing that I am wondering about in your description: how does a `library` use a `port` ? Is that a link that is done at runtime ? If so, how does the component provide the information needed by the library ? Does the library get an RTT dependency by using vizkit3d_debug_drawings ?

**Comment by arneboe** [comment]
> From my point of view having dynamically ports is not a problem as the whole purpose of this library is debugging.

Will they be logged if a `dynamic_output_port` is present in the orogen file?

> One thing that I am wondering about in your description: how does a `library` use a `port` ? Is that a link that is done at runtime ? If so, how does the component provide the information needed by the library ? Does the library get an RTT dependency by using vizkit3d_debug_drawings ?

The `library` dynamically links `vizkit3d_debug_drawing`.  Draw calls create command objects and forward them to `vizkit3d_debug_drawing`. With this pattern the library developer does not know if/where/how the drawing commands are rendered and does not get any dependency other than  `vizkit3d_debug_drawing`.

 `vizkit3d_debug_drawing` can be build with or without RTT dependency. If it is build without RTT port output does not work obviously.

**Comment by doudou** [comment]
Just to make sure ... Given the goals, I think what you've done with `vizkit3d_debug_drawings` is really nice. I'm really keen on having it in rock-core.

About the optional RTT dependency: I guess we could live with that. I would have preferred having the port dispatcher be injected at runtime (implemented in a separate library), but I can live with the status quo.

One thing that bothers me is how one is supposed to configure the library, given that it is per-thread. `configureHook` is for instance not guaranteed to be executed in the same thread as `updateHook`, which makes the scheme fragile IMO - something that can be readily seen by the need for the `NO_THROW` version (YUK !). What's the source of the thread-local requirement ?

Moreover, won't there be interactions between two libraries that would both use vizkit3d_debug_drawings ? (Not a showstopper, trying to understand the limitations).

To get the ports picked up by logging, one would need to have the ports at the minimum created at configure time. I personally am not a big believer in having this kind of resources purely dynamically allocated at runtime (they are, /in fine/, very statically compiled-in the library, and not being able to know what drawings exist is a maintainer's nightmare). What about having a way to declare the channels at the static scope, allowing to pre-create the channels once and for all ?

Something like having a `.hpp` file with a suite of

~~~
VIZKIT3D_DEBUG_DECLARE_CHANNEL(ChannelName);
~~~

which then can be used in the methods as

~~~
void f() {
   DRAW_AXES(ChannelName);
}
~~~

Where VIZKIT3D_DEBUG_DECLARE_CHANNEL registers the channel in a toplevel singleton instance,

~~~
namespace v3dd_channels {
    static char const* const ChannelName = #ChannelName;
}
~~~

and

`PLOT2D(ChannelName)` would statically refer to the channel as e.g. `v3dd_channels::ChannelName`, making sure one doesn't accidentally redefine a channel.

The good side of this is that it opens the way to configure the debug output per-channel, for instance emitting draw calls for some channels, but not for some others. The way things are dispatched could this way also be configured per-channel.

I am however not sure how to maintain backward compatibility with the string scheme you currently have.

**Comment by doudou** [comment]
One thing that's a definite no-no, is the whole paint API being defined at toplevel instead of being in a namespace.

To keep the namespace-ing, I would use inline empty functions instead of macros. The compiler would most probably elide the call altogether.

**Comment by arneboe** [comment]
> One thing that bothers me is how one is supposed to configure the library, given that it is per-thread. `configureHook` is for instance not guaranteed to be executed in the same thread as `updateHook`, which makes the scheme fragile IMO - something that can be readily seen by the need for the `NO_THROW` version (YUK !). What's the source of the thread-local requirement ?

The requirement here was to be able to relate drawings and rock tasks. I.e. figure out which task the port for a specific drawing should be attached to. This was the only feasible idea that I came up with. If you have a better idea how to relate drawings to tasks I am more than willing to implement it. The `NO_THROW` versions are ugly and I would very much like to get rid of them.

> Moreover, won't there be interactions between two libraries that would both use vizkit3d_debug_drawings ? (Not a showstopper, trying to understand the limitations).

If both libraries use the same thread they will use the same command dispatcher. This is not a problem. If they are in different threads each will use its own dispatcher. This might be a problem when both of them use the standalone window because two `QApplication`s will be created, although in different threads. I am not sure if this is a problem. I will create a test case to check...


> What about having a way to declare the channels at the static scope, allowing to pre-create the channels once and for all ?
That would work. The reason I did not do it was because I wanted to avoid splitting declaration and usage. The B-Human framework used such a declarative approach and in my experience it lead to a lot of zombie declarations. I.e. drawings that are declared but no longer in use. 

Instead of creating static strings it would be better to fill a static list. This list could be queried at configuration time to get all existing drawings and thus solve the logging problem.

I'll try to implement the static initializer approach using DECLARE functions. If that works I'll try to move the static initializer code to the draw functions and remove the DECLARE. However this will only work if all draw functions become macros which is something I would like to avoid if possible.

> I am however not sure how to maintain backward compatibility with the string scheme you currently have.

The library has not been officially released. It was used in project Entern but that project is dead and not much of the code survived. I think breaking backward compatibility at this point is fine.

**Comment by arneboe** [comment]
> One thing that's a definite no-no, is the whole paint API being defined at toplevel instead of being in a namespace.
> 
> To keep the namespace-ing, I would use inline empty functions instead of macros. The compiler would most probably elide the call altogether.

I agree, the toplevel api was a bad idea :-)

**Comment by doudou** [comment]
> However this will only work if all draw functions become macros which is something I would like to avoid if possible.

If the initializers live in the namespace of the library, you can refer to them directly (i.e. as object/type/...). If not, one has to refer to them using an explicit namespace, which is fine IMO.

Once the drawings are declared statically, one can set up the dispatcher-to-drawing association at configure time as well - without a need of an implicit per-thread setup - thus solving the other issue.

**Comment by arneboe** [comment]
> Once the drawings are declared statically, one can set up the dispatcher-to-drawing association at configure time as well - without a need of an implicit per-thread setup - thus solving the other issue.

Yes but it solves it with the help of the user (who has to do the configuration). I would like to avoid user interactions as much as possible. If at all possible I would prefer a solution that just works with as little user interaction as possible.

**Comment by arneboe** [comment]
Ok I pushed some changes.

Everything has been moved to the `V3DD` namespace.

All macros have been replaced by functions. This has the downside that side effects in parameters will still be executed. Thus disabled the library no longer leads to zero overhead.

The `thread_local` is gone. There is only one `PortDispatcher` per process now.
The user has to configure the drawings that belong to a certain task in the `configureHook`:
```
bool Task::configureHook()
{
    V3DD::CONFIGURE_DEBUG_DRAWINGS_USE_PORT(this, {"drawing1", "drawing2", "etc"});
```
The string based API remains. I decided against forcing the user to statically declare all drawing channels in advanced. 

The dependency to `orocos_cpp` has been removed. Instead the user has to import the typekit manually inside the orogen file:
```
name "debug_drawing_test"
using_library "vizkit3d_debug_drawings"
import_types_from "vizkit3d_debug_drawings"
task_context "Task" do
    dynamic_output_port /^debug_/, "/boost/shared_ptr</vizkit3dDebugDrawings/CommandBuffer>"
end
```

I will start updating the documentation and testing now :)

**Comment by doudou** [comment]
> The string based API remains. I decided against forcing the user to statically declare all drawing channels in advanced.

The user still has to statically know all drawings channels in advance. He's using ("declaring") them in his code, and needs to know which channels exist to configure them.

By keeping the string interface, you just make it a lot harder to know which drawings can be configured, and thus made it harder to configure them. Your library solves a complex problem. Requiring that the user has to define debug channels does not even register as a cost. I'd go as far as saying that "I want to minimize user interaction" sounds bizarre when the user has to write a lot of complex drawing code to use said library.

> Most of the boilerplate that the user has to write to output from a task could probably be generated using an orogen plugin

There is such things as making things too complex "for the sake of little user interaction". If the "boilerplate" is the need to call `V3DD::CONFIGURE_DEBUG_DRAWINGS_USE_PORT`, it's perfectly fine.

**Comment by arneboe** [comment]
I am looking at this from a library developers point of view. And from this point of view I gain no benefit by being forced to declared channels before usage. For standalone-mode (which I use while developing libraries) declaring channels has no benefit.

However I see your point that further down the line there is some benefit for other users. I'll do some experiments on a branch and see if I can find a way make declaring work without annoying the library developer (i.e. myself :D)

**Comment by doudou** [comment]
TBH, as a library developer, I *hate* when I want to configure logging channels but have no way to know which ones exist.

You are thinking maybe as you as "the sole library developer that knows this library in and out". I get the point of view of "this library maintained over three years by a team of 5 people, which I barely know but that I now have to debug".

**Comment by arneboe** [comment]
Okay I got a prototype more or less working.

```
//macros cannot be part of namespaces, thus I had to add the `V3DD` prefix.
V3DD_DECLARE_DEBUG_DRAWING_CHANNEL("some_channel");
```

```
bool Task::configureHook()
{
    std::vector<std::string> channels;
    V3DD::GET_DECLARED_CHANNELS(channels);
    //somehow filter the channels
    V3DD::CONFIGURE_DEBUG_DRAWINGS_USE_PORT(this, channels);
}
```
Filtering the channels is up to the user. Probably good practice for library developers should be to add some kind of prefix. Or maybe a prefix could be added using a compile time switch. But that could be implemented in a later version. For now I focusing on testing this

**Comment by doudou** [comment]
Is there a reason to keep with the UPPER_CAMEL_CASE style since these are now functions ? It looks weird. For instance, I would expect GET_DECLARED_CHANNELS to return the list of channels, not output through its arguments.

By the way, adding a prefix to macros that are made available outside of your library is the best (only ?) practice. This is also why in C you prefix all functions with the same prefix - working around the lack of namespaces.

**Comment by arneboe** [comment]
> Is there a reason to keep with the UPPER_CAMEL_CASE style since these are now functions ?

Yes, visibility. I want them to stand out, to be distinguishable from the real code.

>  I would expect GET_DECLARED_CHANNELS to return the list of channels, not output through its arguments.

Returning would be nicer, but `disabling` the function is not that nice when it returns something.
With the output parameter the disabled version looks like this
```
void GET_DECLARED_CHANNELS(...){}
```
With return the disabled version looks like this:
```
#include <vector> //forward declaring the stl types is not an option 
#include <string>
std::vector<std::string> GET_DECLARED_CHANNELS(...){ return std::vector<std::string>();}
```
Thus the return-version of the disabled method does still add includes and returns something.

Although the user probably has vector and string included anyway... probably it wont make any difference... I guess I'll change that :)

**Comment by arneboe** [comment]
@doudou  Thanks for the help!
