### ISSUE TITLE
Move osqQt fork from rock.simulation to rock.core for Ubuntu 20.04

### ISSUE THREAD

**Issue by hemker** [rock-core/package_set#188]
Hey,
I'm currently testing a basic rock core stack on my Ubuntu 20.04 machine with the provided QT4 backports. One thing I came across is that openscenegraph-osgQt was removed from openscenegraph and regrouped to an own repository. This is solved within the [rock.simulation package set](https://github.com/rock-simulation/simulation-package_set/blob/master/source.yml), but should be provided in the rock.core package set, as it includes vizkit3d (which needs osgQt).

**Comment by doudou** [comment]
Hi @hemker. To use Rock on 20.04, just use the `qt4_focal` branch of the rock.core package set.

The osgQt package already exists in rock.core, it's called `gui-osg_qt4`.

I'm sorry for the duplicated work. I haven't got the time to fix the remaining issue before we can merge the branch to master (some stuff related to ruby-qt4 bindings require changes in autoproj)
