### ISSUE TITLE
Don't exlude tools/apaka by default

### ISSUE THREAD

**Issue by hemker** [rock-core/package_set#197]
`tools/apaka` is removed from the build configuration by default in `00new_packages.autobuild`. Currently I am working on an automated way to produce various builds with apaka. Thus it is necessary to manually patch every buildconf manifest to contain `- tools/apaka`, otherwise the apaka binaries are not made available via `env.sh`. As every buildconf repo uses a different indentation, this process is unnecessarily complicated.

**Comment by doudou** [comment]
Not in favor. apaka is pulling a lot of dependencies that common rock users really aren't that interested in.

> As every buildconf repo uses a different indentation, this process is unnecessarily complicated.

~~~
 ruby -ryaml -e 'manifest = YAML.load(File.read("autoproj/manifest")); manifest["layout"] << "tools/apaka"; File.write("autoproj/manifest", YAML.dump(manifest))'
~~~

**Comment by hemker** [comment]
Thanks for the script hint. Can live with that :+1:
