### ISSUE TITLE
tools/class_loader missing dependency

### ISSUE THREAD

**Issue by planthaber** [rock-core/package_set#27]
Hi,

class loader is build in debug mode, at least for Ubuntu 14.10 the libpocofoundation9-dbg osdep package is missing, which installs /usr/lib/debug/usr/lib/libPocoFoundationd.so.9.

There are two options to resolve this:

* add the osdep
* build as release

Also see my comment on:
https://github.com/rock-core/package_set/pull/24

**Comment by doudou** [comment]
Fixed by #26. Thanks
