### ISSUE TITLE
bootstrap is broken

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/package_set#94]

**Comment by jmachowinski** [comment]
The Boostrap using the bootstrap.sh is broken.

**Comment by jmachowinski** [comment]
The Bootstrap using the boostrap.sh is broken
wget http://www.rock-robotics.org/bootstrap.sh

if you want master flavor you'll get this error :
 Which flavor of Rock do you want to use ?
    Use 'stable' to use the a released version of Rock that gets updated with bugfixes
    'master' for the development branch
    If you want to use a released version of rock, choose 'stable' and then call 'rock-release switch' after the initial bootstrap
    See http://rock-robotics.org/stable/documentation/installation.html for more information [stable] master
  ERROR: 
  ERROR: You selected the flavor 'master' but '/home/scotch/rock-compile-test/autoproj/overrides.d/25-release.yml' exists.
  ERROR: This means you are on a release; either unselect the release by calling 'rock-release switch master'
  ERROR: or call 'autoproj reconfigure' and select the FLAVOR 'stable'

init.rb(package_set=rock.core):60: exit
  in /home/scotch/rock-compile-test/autoproj/remotes/rock.core/init.rb:60:in `exit'
  in /home/scotch/rock-compile-test/autoproj/remotes/rock.core/init.rb:60:in `<top (required)>'

And an infinite loop of the same question until you choose stable

**Comment by hemker** [comment]
still occurs on Ubuntu 16.04 with autoproj2

**Comment by doudou** [comment]
The package set code needs to be modified to force using 'stable' as the flavor if on a release (i.e. if there is a overrides.d/25-release.yml file)
